config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pages
  resources :portfolios

  # get 'signup', to: 'users#new', as: 'signup' //For Admin only
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :portfolios
    resources :users
    resources :documents
  end
  
  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_many :documents, autosave: true, :dependent => :destroy, foreign_key: "portfolio_id"
  
  accepts_nested_attributes_for :documents, allow_destroy: true
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  layout "admin"

  def index
    # @portfolios = Portfolio.all
    # @portfolios = Portfolio.joins(:documents)
    @portfolios = Portfolio.joins('INNER JOIN documents ON documents.portfolio_id = portfolios.id')
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio = Portfolio.create(portfolio_params)
    @portfolio.documents.create(document_params)
    
    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @portfolio] }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @portfolio] }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:name, :describtion, documents_attributes: [:id, :file])
    end

    def document_params
      params.require(:portfolio).permit(:file)
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show]

  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Describtion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.describtion %></td>
        <td><img src="<%= url_for(:controller => "documents", 
                      :action => "show", 
                      :id => portfolio.document_id) %>" width="200" height="200"/></td>
        <td><%= link_to 'Show', portfolio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Describtion:</strong>
  <%= @portfolio.describtion %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>