config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pages
  resources :portfolios

  # get 'signup', to: 'users#new', as: 'signup' //For Admin only
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :portfolios
    resources :users
    resources :documents
  end
  
  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_many :documents, autosave: true, :dependent => :destroy, foreign_key: "portfolio_id"
  
  accepts_nested_attributes_for :documents, allow_destroy: true
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  layout "admin"

  def index
    # @portfolios = Portfolio.all
    # @portfolios = Portfolio.joins(:documents)
    @portfolios = Portfolio.joins('INNER JOIN documents ON documents.portfolio_id = portfolios.id')
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
  end

  def edit
  end

  def create
    @portfolio = Portfolio.create(portfolio_params)
    @portfolio.documents.create(document_params)
    
    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: [:admin, @portfolio] }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @portfolio] }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to admin_portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:name, :describtion, documents_attributes: [:id, :file])
    end

    def document_params
      params.require(:portfolio).permit(:file)
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show]

  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/admin/portfolios/_form.html.erb
<%= form_for([:admin, @portfolio]) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :describtion %><br>
    <%= f.text_area :describtion %>
  </div>
  <%= image_tag '', class: 'image_to_upload', width: 200, height: 200 %>

  <div class="field">
    <%= f.file_field :file, class: 'photo_upload'  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_portfolios_path(@portfolio) %> |
<%= link_to 'Back', admin_portfolios_path %>

app/views/admin/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<section class="group">
  <%= debug(@portfolios) %>
  <% @portfolios.each do |portfolio| %>
  <div class="col-4">
    <div class="portfolios">
      <img src="<%= url_for(:controller => "documents", 
            :action => "show", 
            :id => 4) %>" width="100%"/>
      <div class="desc">
        <h2><%= portfolio.name %></h2>
        <p><%= portfolio.describtion %></p>
        <p><%= portfolio.created_at %></p>
      </div>
      <div><%= link_to 'Show', admin_portfolio_path(portfolio) %></div>
      <div><%= link_to 'Edit', edit_admin_portfolio_path(portfolio) %></div>
      <div><%= link_to 'Destroy', admin_portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
  </div>
  <% end %>
  <%#= Time.zone.now %>
</section>

<%= link_to 'New Portfolio', new_admin_portfolio_path %>

<div id="fizzbuzz">
  <% for i in 1..100
    #Not Modulus 3 || 5
    mod3 = i%3 == 0
    mod5 = i%5 == 0

    default = mod3 || mod5 ? "" : i
    fizz = mod3 ? "Fizz" : default
    result = mod5 ? "#{fizz}Buzz" : fizz %>
    <p><%#= result %></p>
  <% end %>
</div>

<style type="text/css">
  #fizzbuzz > p {
    display: inline-block;
    padding: 10px;
  }
</style>

app/views/admin/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_portfolios_path %>

app/views/admin/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Describtion:</strong>
  <%= @portfolio.describtion %>
</p>

<%= link_to 'Edit', edit_admin_portfolio_path(@portfolio) %> |
<%= link_to 'Back', admin_portfolios_path %>