config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pages
  resources :portfolios

  # get 'signup', to: 'users#new', as: 'signup' //For Admin only
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :portfolios
    resources :users
    resources :documents
  end
  
  root to: "pages#home"
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :portfolio, foreign_key: "portfolio_id"

  validate :file_size_limit

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
      self.filename = sanitize_filename(@file.original_filename)
      self.content_type = @file.content_type
      self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_limit
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'File size cannot be over 1MB.')
      end
    end

end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  layout "admin"

  def index
    @documents = Document.all
  end

  def show
#    @document = Document.find(params[:id])
    send_data(@document.file_contents,
              type: @document.content_type,
              filename: @document.filename,
              :disposition => 'inline')
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    
    @document.render

    respond_to do |format|
      if @document.save
        format.html { redirect_to admin_documents_url, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: [:admin, @document] }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def edit
  end

  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to admin_documents_url, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @document] }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to admin_documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
        params.require(:document).permit(:file)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show]

  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
    send_data(@document.file_contents,
              type: @document.content_type,
              filename: @document.filename,
              :disposition => 'inline')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end
end

app/views/admin/documents/_form.html.erb
<%= form_for([:admin, @document]) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= image_tag '', class: 'image_to_upload', width: 200, height: 200 %>

  <div class="field">
    <%= f.file_field :file, class: 'photo_upload'  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_documents_path(@document) %> |
<%= link_to 'Back', admin_documents_path %>

app/views/admin/documents/index.html.erb
<h1>List Images</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><img src="<%= url_for(:controller => "documents", 
                      :action => "show", 
                      :id => document.id) %>" width="200" height="200"/>;</td>
        <td><%= link_to 'Show', document %></td>
        <td><%= button_to 'Download', document, method: :get %></td>
          <td><%= button_to 'Destroy', admin_document_path(document), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_admin_document_path %>

app/views/admin/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>