config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pages
  resources :portfolios

  # get 'signup', to: 'users#new', as: 'signup' //For Admin only
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :portfolios
    resources :users
    resources :documents
  end
  
  root to: "pages#home"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username,
    presence: true,
    uniqueness: true
    # format: { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize
  
  layout "admin"

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: [:admin,@user] }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  private
    def set_user
      @user = Portfolio.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :username, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.username %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>  
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>